### ISSUE TITLE
Support to download another modules

### ISSUE THREAD

**Issue by felipemeamaral** [lucasg/powershell-docset#1]
Your script helped me a lot to export all Microsoft documentation to a Dash doc file.
But, it'll be way better if you could add another modules support like:

`Windows 10 and Windows Server 2016 PowerShell, Microsoft Desktop Optimization and others.`

Powershell has a bunch of additional modules developed by microsoft to add more features to the language.
Thank you for your work.

**Comment by lucasg** [comment]
Oh shit they weren't present when I wrote the scraper, that's awesome ! I'll add it to the script whenever I have the time.

**Comment by lucasg** [comment]
I've added win10 modules to the scraper. It should be available since v.0.6.
